root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'react-hooks'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  'react/react-in-jsx-scope': 'off'
  'react-hooks/rules-of-hooks': 'error'
  'react-hooks/exhaustive-deps': 'warn'
  'jsx-a11y/anchor-is-valid': 'off' # it's impossible to satisfy this rule using next/link
  'semi': 'error'
