query GetCategory($id: Int!) {
  getCategory(id: $id) {
    id
    name
    tests {
      id
      name
      maxScore
      creator {
        id
        name
      }
      questions {
        id
      }
      results {
        id
        score
      }
    }
  }
}

mutation DeleteTest($id: Int!) {
  deleteTest(id: $id)
}
