query GetProfile($id: Int!) {
  getProfile(id: $id) {
    id
    name
    email
    role
    tests {
      id
      name
      maxScore
      questions {
        id
      }
      results {
        id
        score
      }
    }
    results {
      id
      score
      test {
        id
        name
        maxScore
      }
    }
  }
}

mutation EditProfile($input: EditProfileInput!) {
  editProfile(input: $input) {
    id
    name
    email
    role
    tests {
      id
      name
    }
  }
}
