exports.seed = (knex, Promise) => Promise.all([
  knex('answer').insert([
    { question_id: 3, text: 'вспомнить о зеленой обезьяне', correct: 1 },
    { question_id: 3, text: 'я и так о нем не думаю, другие вещи затмевают его', correct: 1 },
    { question_id: 3, text: 'Понятия не имею, теперь сидит в башке', correct: 0 },
    { question_id: 3, text: 'прошу помощи зала', correct: 0 },
    { question_id: 2, text: 'Потому что Он лошара', correct: 0 },
    { question_id: 2, text: 'Физика преподнесла свое возмездие', correct: 1 },
    { question_id: 1, text: 'Быть', correct: 1 },
    { question_id: 1, text: 'Не быть', correct: 0 },
    { question_id: 7, text: 'Вы серьезно? У меня всегда всё получается, даже то, что не нужно.', correct: 1 },
    { question_id: 7, text: 'Ничего не получается, и вообще я лох', correct: 0 },
    { question_id: 5, text: 'Перемены - мое второе имя', correct: 1 },
    { question_id: 5, text: 'Я боюсь дестабилизации своей жизни', correct: 0 },
    { question_id: 4, text: 'Ананасы 0_о омг....', correct: 1 },
    { question_id: 4, text: 'беееее', correct: 0 },
    { question_id: 8, text: 'Я сама уверенность', correct: 1 },
    { question_id: 8, text: 'Я даже познакомиться стремаю, о чем Вы?', correct: 0 },
    { question_id: 6, text: 'Выгода', correct: 1 },
    { question_id: 6, text: 'Компромисс', correct: 1 },
  ]),
  knex('category').insert([
    { name: 'Курс 1' },
    { name: 'Курс 2' },
    { name: 'Курс 3' },
    { name: 'Курс 4' },
    { name: 'Методические тесты' }
  ]),
  knex('question').insert([
    { test_id: 1, text: 'Быть или не быть?' },
    { test_id: 1, text: 'Почему яблоко упало на ученного?' },
    { test_id: 1, text: 'Как перестать думать о белом тигре?' },
    { test_id: 1, text: 'Вы любите ананасы?' },
    { test_id: 17, text: 'Вы готовы к переменам?' },
    { test_id: 17, text: 'Что вас стимулирует больше всего?' },
    { test_id: 11, text: 'Вам часто кажется, что у вас все получиться?' },
    { test_id: 11, text: 'Вы уверенный в себе человек?' }
  ]),
  knex('test').insert([
    { category_id: 1, name: 'Тест на конфликтность' },
    { category_id: 1, name: 'Тест на уверенность' },
    { category_id: 1, name: 'Тест на страстность' },
    { category_id: 1, name: 'Тест на оптимизм' },
    { category_id: 1, name: 'Тест на смелость' },
    { category_id: 2, name: 'Тест на организаторские способности' },
    { category_id: 2, name: 'Тест на самоуправление' },
    { category_id: 2, name: 'Тест на находчивость' },
    { category_id: 2, name: 'Тест на честолюбие' },
    { category_id: 3, name: 'Тест на предпринимательскую креативность' },
    { category_id: 3, name: 'Тест на умение принимать решения' },
    { category_id: 3, name: 'Тест на толерантность' },
    { category_id: 4, name: 'Тест на этику поведения в бизнесе' },
    { category_id: 4, name: 'Тест работодателя' },
    { category_id: 4, name: 'Адаптивность' },
    { category_id: 5, name: 'Методика "Мотивы профессиональной деятельности"' },
    { category_id: 5, name: 'Методика "Личностная готовность к переменам"' },
    { category_id: 5, name: 'Опросник "Карьерные ориентации"' }
  ])
]);
